S02 us1.3 aside
WildCodeSchool-2023-09/php-p2-straszik pull request #10
Opened 2023-11-08 14:45 UTC by Kynuak

Ajout du menu aside sur la page d'accueil et ajout d'un nouveau layout en fonction pour les pages qui auront besoin d'un layout.
Ajout du component aside avec les réseaux + newsletter et insert dans la BDD + lien boutique

2023-11-08 14:51 UTC, JessKel approved these changes

2023-11-08 14:51 UTC, Narco79 approved these changes

2023-11-08 20:37 UTC, vincentr-wcs requested changes

2023-11-08 20:37 UTC, vincentr-wcs commented on public/assets/css/home.css
> +}
Tu pourrais mettre cette propriété dans le _global.css tu utilises déjà le sélecteur non ?

2023-11-08 20:37 UTC, vincentr-wcs commented on src/Controller/HomeController.php
> +        $data = array_map('htmlentities', $data);
Pas besoin de faire le htmlentities, twig s'en occupe nativement

2023-11-08 20:37 UTC, vincentr-wcs commented on src/Model/Component/AsideManager.php
> +    public function verifNewsletter(array $verif): array
Attention dans le manager on ne met uniquement ce qui concerne la BDD donc les requêtes en BDD. Là c'est une fonction qui vérifie que les champs sont bien rempli et les affichent en front donc c'est le controller qui gère cette logique.

2023-11-08 20:37 UTC, vincentr-wcs commented on src/View/Discography/discography.html.twig
> +{% block stylesheet %}<link rel="stylesheet" href="/assets/css/discography.css">{% endblock %}
A enlevé normalement avec ce qu'on a fait avec Jessica on a plus besoin de faire ça.

2023-11-08 20:37 UTC, vincentr-wcs commented on src/View/Home/index.html.twig
> +{% block stylesheet %}<link rel="stylesheet" href="/assets/css/home.css">{% endblock %}
Même remarque qu'à Jessica. Si vous avez commencé à importer tous vos fichiers de style dans le fichier style.css vaut mieux garder cette façon de procéder jusqu'au bout.

2023-11-08 20:52 UTC, Kynuak commented on public/assets/css/home.css
> +}
C'est vrai, j'avais rajouter le sélecteur général après pour le font-family

2023-11-08 20:52 UTC, Kynuak commented on src/Controller/HomeController.php
> +        $data = array_map('htmlentities', $data);
Ah ! je ne savais pas !

2023-11-08 20:54 UTC, Kynuak commented on src/Model/Component/AsideManager.php
> +    public function verifNewsletter(array $verif): array
D'acc !

2023-11-09 09:18 UTC, vincentr-wcs approved these changes
Super boulot !

2023-11-09 09:18 UTC, merged