S02 us3.2 fix card group
WildCodeSchool-2023-09/php-p2-straszik pull request #13
Opened 2023-11-09 10:11 UTC by Narco79

Correction du css de la page

2023-11-09 10:31 UTC, Kynuak approved these changes
Top !

2023-11-09 10:32 UTC, JessKel approved these changes
Nickel

2023-11-09 20:55 UTC, vincentr-wcs requested changes
Parfait y'a juste deux petits changements !

2023-11-09 20:55 UTC, vincentr-wcs commented on public/assets/css/_groupe.css
> +    font-size: 40px;
La font-size on évite de la mettre en px c'est pas une unité responsive vaut mieux la mettre en rem

2023-11-09 20:55 UTC, vincentr-wcs commented on public/assets/css/_groupe.css
>      font-size: 20px;
idem ici j'avais pas vu

2023-11-10 08:49 UTC, vincentr-wcs approved these changes

2023-11-10 08:49 UTC, merged