Fixconcert
WildCodeSchool-2023-09/php-p2-straszik pull request #22
Opened 2023-11-14 14:31 UTC by NyroLobo

nouvelle merge

2023-11-14 14:36 UTC, JessKel approved these changes
C'est bon pour moi. Je vais juste supprimer sur une nouvelle branche l'import de groupe.css qui est en double.

2023-11-14 14:43 UTC, Kynuak approved these changes

2023-11-14 20:51 UTC, vincentr-wcs requested changes

2023-11-14 20:51 UTC, vincentr-wcs commented on src/View/Concert/billetterie.html.twig
> +    </head>
Pourquoi il y'a du PHP ici ? Les requêtes sur la bdd se font dans le dossier manager pas dans les fichiers twig.

2023-11-14 20:51 UTC, vincentr-wcs commented on src/View/Concert/billetterie.html.twig
> +<body>
Tu extends du layout et le block content est dans le body donc tu n'as pas besoin de la remettre. Tu es déjà dans le body quand tu écris dans le block content

2023-11-14 20:51 UTC, vincentr-wcs commented on src/View/Concert/billetterie.html.twig
> +                echo $concert['date']; ?>| 20h </div>
On est dans un fichier twig on ne fait de if comme ça. On fait le if en twig

2023-11-14 20:51 UTC, vincentr-wcs commented on src/View/Concert/billetterie.html.twig
> +                echo $concert['date']; ?>| 20h </div>
Lien de la doc : https://twig.symfony.com/doc/3.x/tags/if.html

2023-11-14 20:51 UTC, vincentr-wcs commented on src/View/Concert/billetterie.html.twig
> +            <div> STRASBOURG| <?php echo $concert['location'];?> </div>
Il faut tout mettre en twig pas de balise php

2023-11-14 20:51 UTC, vincentr-wcs commented on src/View/Concert/billetterie.html.twig
> +            <div> Place disponible(s): <?php echo $concert['places_availables'];?> </div>
Il faut tout mettre en twig pas de balise php

2023-11-14 20:51 UTC, vincentr-wcs commented on src/View/Concert/billetterie.html.twig
> +</html>
pas besoin des balises fermantes body et html

2023-11-14 20:51 UTC, vincentr-wcs commented on src/View/Concert/billetterie.html.twig
> +    <script src="https://cdn.jsdelivr.net/npm/uikit@3.17.5/dist/js/uikit.min.js"></script></body>
le script de uikit est déjà dans le layout en faisant un extends tu l'hérites dans ce fichier pas besoin de le remettre

2023-11-16 07:29 UTC, vincentr-wcs commented
Conflits à régler @JessKel @NyroLobo

2023-11-16 07:55 UTC, JessKel approved these changes
Impeccable

2023-11-16 08:15 UTC, Kynuak commented
Je me suis permis de régler les conflits Vincent.

2023-11-16 10:14 UTC, vincentr-wcs requested changes

2023-11-16 10:14 UTC, vincentr-wcs commented on src/Controller/GoodiesController.php
> -        }
C'est normal que toute cette partie soit enlevée ?

2023-11-16 10:14 UTC, vincentr-wcs commented on src/Controller/GoodiesController.php
> -    }
Idem ici

2023-11-16 10:18 UTC, Kynuak commented on src/Controller/GoodiesController.php
> -        }
Oui car j'ai changer le fonctionnement de l'inscription sur la newsletter le AsideManager n'existe plus. C'est en cohérence avec ma PR newsletter que j'ai fait hier

2023-11-16 10:18 UTC, Kynuak commented on src/Controller/GoodiesController.php
> -    }
La meme chose que précedemment

2023-11-16 10:23 UTC, vincentr-wcs commented on src/Controller/GoodiesController.php
> -        }
D'acc super 👍

2023-11-16 10:24 UTC, vincentr-wcs approved these changes
Bien joué !

2023-11-16 10:24 UTC, merged