ajout de la fonctionnalite de connexion
WildCodeSchool-2023-09/php-p2-straszik pull request #27
Opened 2023-11-16 09:01 UTC by PALVAREZ67

2023-11-16 09:18 UTC, JessKel approved these changes
Ca parait ok

2023-11-16 10:03 UTC, Narco79 approved these changes

2023-11-16 10:23 UTC, Kynuak commented on src/View/layout.html.twig
> +			{{ dump(session)}}
var_dump en trop, il faudrait le retirer

2023-11-16 10:24 UTC, Kynuak commented on src/Controller/UserController.php
> +                    $_SESSION['status'] = $userData['status (admin/client)'];
Et ici, il faudrait changer le $userData['status (admin/client)"] par juste ['status']

2023-11-16 10:25 UTC, Kynuak requested changes
Il faudrait changer les petites choses @PALVAREZ67

2023-11-16 10:42 UTC, vincentr-wcs commented
@PALVAREZ67 conflits à régler

2023-11-16 14:22 UTC, Kynuak approved these changes
Top

2023-11-16 20:22 UTC, vincentr-wcs commented
@PALVAREZ67 Encore un conflit dû à l'acceptation de la dernière PR :)

2023-11-16 21:00 UTC, vincentr-wcs requested changes
Bon travail juste deux 3 petits modifs

2023-11-16 21:00 UTC, vincentr-wcs commented on src/Controller/UserController.php
> +namespace APP\Controller;
Attention ici le app doit être comme ça : 
```suggestion
namespace App\Controller;
```

2023-11-16 21:00 UTC, vincentr-wcs commented on src/Controller/UserController.php
> +            'sessionData' => $_SESSION]
Pas besoin de renvoyer la variable $_SESSION elle est déjà disponible dans une variable qui est disponible dans tous les templates avec ce que tu as fait dans AbstractController

2023-11-16 21:00 UTC, vincentr-wcs commented on src/View/Admin/connection.html.twig
> +					<input class="uk-input" type="mail" aria-label="Not clickable icon" name="email" label=" email">
Le type mail n'existe pas c'est email
```suggestion
					<input class="uk-input" type="email" aria-label="Not clickable icon" name="email" label=" email">
```

2023-11-20 09:19 UTC, JessKel approved these changes
ok pour moi !

2023-11-20 11:20 UTC, vincentr-wcs approved these changes

2023-11-20 11:20 UTC, merged