ajout de la page gestion des utilisateurs
WildCodeSchool-2023-09/php-p2-straszik pull request #33
Opened 2023-11-19 22:56 UTC by JessKel

2023-11-19 23:13 UTC, Kynuak commented on src/Controller/UsersAdminController.php
> +            if (isset($_POST['delete'])) {
Tu as oublié de retirer ce if.

2023-11-19 23:14 UTC, Kynuak commented on src/Model/UsersAdminManager.php
> +        $statement = $this->pdo->prepare("UPDATE " . self::TABLE . "
Tu as oublié de mettre le mot de passe dans la requete

2023-11-19 23:18 UTC, Kynuak commented on src/View/Admin/UsersAdmin/Includes/_form_users_admin.html.twig
> +            <label class="uk-form-label"for="form-stacked-text">Status</label>
Je pense qu'ici c'était mieux de mettre un select Admin / Utilisateur non ?
Comme ça l'admin c'est tout de suite quoi mettre

2023-11-19 23:19 UTC, Kynuak requested changes
On reverra ça ensemble demain pour les deux trucs :)

2023-11-20 06:27 UTC, PALVAREZ67 approved these changes

2023-11-20 08:58 UTC, JessKel commented on src/Model/UsersAdminManager.php
> +        $statement = $this->pdo->prepare("UPDATE " . self::TABLE . "
C'est volontaire car l'admin n'a pas à changer le mot de passe de l'utilisateur (il y a un formulaire de changement de mot de passe). Du coup, j'ai enlevé le mot de passe partout dans les formulaires admin.

2023-11-20 09:16 UTC, JessKel commented on src/View/Admin/UsersAdmin/Includes/_form_users_admin.html.twig
> +            <label class="uk-form-label"for="form-stacked-text">Status</label>
C'est fait !

2023-11-20 09:16 UTC, Kynuak approved these changes

2023-11-20 11:24 UTC, vincentr-wcs approved these changes

2023-11-20 11:24 UTC, merged