Ajout page actus + corrections navbar + correction discographie + MAJ…
WildCodeSchool-2023-09/php-p2-straszik pull request #9
Opened 2023-11-07 15:18 UTC by JessKel

Ajout page actus + modifications CSS global, style.css, navbar + modification navbar + corrections page discography

2023-11-07 15:34 UTC, Kynuak approved these changes
Top !

2023-11-07 15:39 UTC, PALVAREZ67 approved these changes

2023-11-07 20:20 UTC, vincentr-wcs requested changes

2023-11-07 20:20 UTC, vincentr-wcs commented on public/assets/css/actus.css
> +#actu-heading-line {
On évite en css d'utiliser les id. Vaut mieux utiliser des class, c'est mieux pour le maintien du code et ça permet de le réutiliser si un élément du site se comporte de la même manière. Pas une obligation de changer mais si tu as le temps n'hésite pas à le faire

2023-11-07 20:20 UTC, vincentr-wcs commented on public/assets/css/style.css
> -@import url("_groupe.css");
C'est normal que tu es enlevé ces deux lignes d'import ?

2023-11-07 20:20 UTC, vincentr-wcs commented on src/View/Discography/discography.html.twig
> +{% block stylesheet %}<link rel="stylesheet" href="assets/css/discography.css">{% endblock %}
Pourquoi remettre une deuxième fois la feuille de style ? Elle est importée dans le style.css qui est lui dans le layout. Donc pas besoin de remettre la feuille de style ici

2023-11-08 11:48 UTC, vincentr-wcs approved these changes
SUper travail !

2023-11-08 11:48 UTC, merged